import song

TOP_TEN_SONGS = [
    song.Song(title="Psycho",
                artist_name="Post Malone",
                youtube_url="https://www.youtube.com/watch?v=au2n7VVGv_c"),
    song.Song(title="The Spotlight",
                artist_name="Logic",
                youtube_url="https://www.youtube.com/watch?v=fPEsDF5WL1w"),
    song.Song(title="Faint",
                artist_name="Linkin Park",
                youtube_url="https://www.youtube.com/watch?v=LYU-8IFcDPw"),
    song.Song(title="What I've Done",
                artist_name="Linkin Park",
                youtube_url="https://www.youtube.com/watch?v=8sgycukafqQ"),
    song.Song(title="Dead Memories",
                artist_name="Slipknot",
                youtube_url="https://www.youtube.com/watch?v=9gsAz6S_zSw"),
    song.Song(title="Remember The Name",
                artist_name="Fort Minor",
                youtube_url="https://www.youtube.com/watch?v=VDvr08sCPOc"),
    song.Song(title="Kenji",
                artist_name="Fort Minor",
                youtube_url="https://www.youtube.com/watch?v=pUBKcOZjX6g"),
    song.Song(title="Ride",
                artist_name="twenty one pilots",
                youtube_url="https://www.youtube.com/watch?v=Pw-0pbY9JeU"),
    song.Song(title="Before I forget",
                artist_name="Slipknot",
                youtube_url="https://www.youtube.com/watch?v=qw2LU1yS7aw"),
    song.Song(title="Sinner",
                artist_name="Veorra",
                youtube_url="https://www.youtube.com/watch?v=M99E8pgT3N4")
]
